### ISSUE TITLE
gulp throws error

### ISSUE THREAD

**Issue by peterlu-hinter** [lithiumtech/lithium-sdk#122]
How to reproduce:

run a docker image FROM node:4.8.4
npm install gulp@3.9.1 -g
npm install lithium-sdk@1.7.0 -g

after creating a sdk project, when run "li export-studio-plugin", I am getting a gulp error.
If I install lithium-sdk@1.4.1, I am not getting the error.
lithium-sdk@1.6.0 has the same error.

============================================

root@5248716427c6:/usr/src/app/sdk# li export-studio-plugin
/usr/local/lib/node_modules/lithium-sdk/node_modules/dependency-tree/index.js:181
    config.visited[config.filename].push(...subTree);
                                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/lithium-sdk/lib/component-dependencies.js:3:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/usr/local/lib/node_modules/lithium-sdk/gulp/scripts.js:5:32)
    at module.exports (/usr/local/lib/node_modules/lithium-sdk/gulp/includes.js:37:23)

**Comment by dav-ayman** [comment]
This issue is being closed as part of the repository cleanup process.

If you believe this issue should remain open, please contact me:
- Slack: @c-david.ayman
- Email: c-david.ayman@khoros.com

Action performed by: @dav-ayman
Date: 06/13/2025
