### ISSUE TITLE
li serve-sass broken with 16.6 Responsive Skin

### ISSUE THREAD

**Issue by RobTDev** [lithiumtech/lithium-sdk#58]
The following is thrown when attempting to run li serve-sass after upgrading an environment to 16.6 or later with a fresh responsive skin created in Studio, tested and replicated on multiple machines with new skins, every instance fails.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: res/skins/community-responsive/sass/skin.scss
Error: File to import not found or unreadable: responsive_peak/sass/vendor
       Parent style sheet: stdin
        on line 12 of stdin
>> @import 'responsive_peak/sass/vendor';
   ^

    at options.error (/usr/local/lib/node_modules/lithium-sdk/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:292:26)
```

On a new machine installing the SDK and downloading the plugin for the first time then initiating li serve-sass for it's first run will return the following:

```
[09:11:33] Loaded gulp tasks in: 262 ms
[09:11:33] Using gulpfile ~/Git-Repositories/responsive/gulpfile.js
[09:11:33] Starting 'watch-res-sass'...
[09:11:33] No directory found under coreplugins for res/feature/responsivepeak/. Returning default
[09:11:33] No directory found under coreplugins for res/feature/responsivepeak/. Returning default
[09:11:33] No directory found under coreplugins for res/feature/responsivepeak/. Returning default
[09:11:33] No directory found under coreplugins for res/feature/responsivepeak/. Returning default
[09:11:33] No directory found under coreplugins for res/feature/responsivepeak/. Returning default
[09:11:33] Finished 'watch-res-sass' after 383 ms
[09:11:33] Server started http://localhost:9000
[09:12:04] core plugin downloaded successfully


events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: res/skins/community-responsive/sass/skin.scss
Error: File to import not found or unreadable: responsive_peak/sass/vendor
       Parent style sheet: stdin
        on line 12 of stdin
>> @import 'responsive_peak/sass/vendor';
   ^

    at options.error (/usr/local/lib/node_modules/lithium-sdk/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:292:26)
```

**Comment by dav-ayman** [comment]
This issue is being closed as part of the repository cleanup process.

If you believe this issue should remain open, please contact me:
- Slack: @c-david.ayman
- Email: c-david.ayman@khoros.com

Action performed by: @dav-ayman
Date: 06/13/2025
