### ISSUE TITLE
Cannot find module 'isarray': error during `li set-responsive-options`

### ISSUE THREAD

**Issue by c-stone** [lithiumtech/lithium-sdk#72]
While running `li set-responsive-options` for the first time, I receive the following error:
```
cstone$ li set-responsive-options
module.js:474
    throw err;
    ^

Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cstone/.nvm/versions/node/v7.1.0/lib/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:25:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by c-stone** [comment]
getting the same issue tying to submit the plugin
```
cstone$ li submit-plugin
module.js:474
    throw err;
    ^

Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cstone/.nvm/versions/node/v7.1.0/lib/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:25:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by c-stone** [comment]
removing and reinstalling `node_modules` seemed to help so far.

**Comment by dougschroeder** [comment]
Closing with the above resolution (remove and reinstall `node_modules`).
