### ISSUE TITLE
li create-skin no such file or directory bug

### ISSUE THREAD

**Issue by mobot11** [lithiumtech/lithium-sdk#83]
Hi, I have the Lithium SDK set up on Node version 8.9.4. I am able to push quilts and components to the staging server. However when I run `li create-skin --clearCore` or `li create-skin` I get the following error message after entering my skin name

```
readline.js:1021
            throw err;
            ^

Error: ENOENT: no such file or directory, stat '/Users/dylanmoberg/dev/lithium/www-community-com/coreplugin/other/res/skins/theme_support'
    at Object.fs.statSync (fs.js:948:11)
    at findBaseDirForSkin (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:184:12)
    at Skin.getParent (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:289:39)
    at /Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:326:29
    at getAttrib (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:200:24)
    at Skin.isResponsive (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:322:14)
    at /Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:79:19
    at Array.filter (<anonymous>)
    at getLocalResponsiveSkins (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:78:8)
    at Object.getResponsiveSkins (/Users/dylanmoberg/.nvm/versions/node/v8.9.4/lib/node_modules/lithium-sdk/lib/skin.js:344:53)
```

I have looked through the developer community and GitHub issues but not found a fix.

**Comment by mobot11** [comment]
Fixed with the last comment here https://community.lithium.com/t5/Developer-Discussion/SDK-bootstrap-base-no-such-file-or-directory/m-p/264740 by just creating the missing directory. Adding a file to core seems like a hack to fix this bug.
